Initial commit of Visualization
actlab-fhy/f-DFG-model-explorer pull request #1
Opened 2024-07-25 22:50 UTC by Subashkatel

2024-07-26 20:50 UTC, christopherpriebe requested changes
Look at comments. Also, remove the pictures; they are outdated anyways.

2024-07-26 20:50 UTC, christopherpriebe commented on model.json
> +{
Please delete this entire file from the PR; this doesn't need to be committed.

2024-07-26 20:50 UTC, christopherpriebe commented on pyproject.toml
> +name = "my-adapter"
Please update this file and add a bit more information. For example, rename it to the name of the repo or something.

2024-07-26 20:50 UTC, christopherpriebe commented on src/f-DFG-model-explorer/main.py
> +        # this is required to call the parent class's __init__ method
This comment is useless; remove

2024-07-26 20:50 UTC, christopherpriebe commented on src/f-DFG-model-explorer/main.py
> +import json
Missing a module-level docstring.

2024-07-26 20:50 UTC, christopherpriebe commented on src/f-DFG-model-explorer/main.py
> +def get_node_style(node_kind: str, node_type: str) -> graph_builder.GraphNodeStyle:
This function needs a docstring as well.

2024-07-28 00:44 UTC, Subashkatel commented
Made all the requested changes let me know if I missed anything.

2024-07-29 20:25 UTC, christopherpriebe requested changes

2024-07-29 20:25 UTC, christopherpriebe commented on src/f-DFG-model-explorer/main.py
> +This module provides functionality to convert Networkx JSON files into Model Explorer graphs.
*NetworkX

2024-07-29 20:25 UTC, christopherpriebe commented on src/f-DFG-model-explorer/main.py
> +        node_kind (str): kind of the node
Capitalize first word in the description and add period at the end. Apply this to all the functions

2024-07-29 20:25 UTC, christopherpriebe commented on .gitignore
> +.json
There is a file called ".json"? Add the wildcard operator before if you meant any .json file.

2024-07-29 20:29 UTC, Spill-Tea requested changes

2024-07-29 20:29 UTC, Spill-Tea commented on src/f-DFG-model-explorer/main.py
> +class NodeKeys:
It might make more sense for this NodeKeys Base class to have a class method, since separate private functions are created to extract key value pairs for every subclass.

Something like this:

```python
class NodeKeys:
    @classmethod
    def get(cls, node_data: dict) -> list[KeyValue]:
        """Retrieve relevant attributes of a node."""
        return []

```

2024-07-29 20:29 UTC, Spill-Tea commented on README.md
> +$ model-explorer example.json --extension=fdfg_visualizer
Update usage instructions to use updated project extension name.

2024-07-30 16:44 UTC, Subashkatel commented on src/f-DFG-model-explorer/main.py
> +        node_kind (str): kind of the node
Do you me first letter or word?

2024-07-30 23:16 UTC, Spill-Tea approved these changes
lgtm

2024-07-31 17:26 UTC, christopherpriebe approved these changes
lgtm

2024-07-31 19:48 UTC, merged